name: Deploy to DEV Org

on:
  push:
    branches:
      - DEV

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce
        run: sf org login jwt --client-id ${{ secrets.SF_CLIENT_ID }} --jwt-key-file server.key --username ${{ secrets.SF_USERNAME }} --set-default

      - name: Deploy to DEV Org
        run: sf project deploy start --target-org ${{ secrets.SF_USERNAME }} --test-level RunLocalTests