name: Deploy to DEV Org

on:
  push:
    branches:
      - DEV

jobs:
  deploy-to-salesforce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SF_AUTH_URL }}" > authfile.txt
          sf org login sfdx-url -f authfile.txt --set-default
          rm authfile.txt

      - name: Deploy to DEV Org
        run: sf project deploy start --test-level RunLocalTests